# Based off https://github.com/rapidsai/cudf/blob/branch-25.02/.github/workflows/pandas-tests.yaml
name: Test dask-upstream

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  dask-tests:
      # run the Dask and Distributed unit tests
      secrets: inherit
      uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-25.02
      with:
        # This selects "ARCH=amd64 + the latest supported Python + CUDA".
        matrix_filter: map(select(.ARCH == "amd64")) | group_by(.CUDA_VER|split(".")|map(tonumber)|.[0]) | map(max_by([(.PY_VER|split(".")|map(tonumber)), (.CUDA_VER|split(".")|map(tonumber))]))
        build_type: nightly
        branch: ${{ inputs.branch }}
        date: ${{ inputs.date }}
        sha: ${{ inputs.sha }}
        script: scripts/run.sh